# Generated by Django 2.1.5 on 2019-02-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_postagem_imagem_postagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curtidas', models.IntegerField()),
                ('curtidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curti', to='perfis.Perfil')),
            ],
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AddField(
            model_name='curtida',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_curtidas', to='perfis.Postagem'),
        ),
    ]
